services:
  - type: web
    name: fiascha-portal
    env: python
    buildCommand: pip install -r requirements.txt && flask db upgrade
    startCommand: gunicorn run:app
    envVars:
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: fiascha-db
          property: connectionString

databases:
  - name: fiascha-db
    plan: free
